import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="navbar">
      <Link href="/">홈</Link>
      <Link href="/list">List</Link>
      <Link href="/board">게시판</Link>
      </div>
      {children}
      </body>
    </html>
  );
}
